### ISSUE TITLE
Sklonjenje slova "sam" jest slomjeno/zlamano

### ISSUE THREAD

**Issue by noomorph** [medzuslovjansky/js-utils#10]
**Avtor:** @EGYTfromFDTE

![зображення](https://github.com/sonic16x/interslavic/assets/113429882/f43bd686-7750-45e2-9cc1-56f156ae983d)

**Comment by noomorph** [comment]
I "ono" takože
![зображення](https://github.com/sonic16x/interslavic/assets/113429882/e024d433-f07f-48e3-af0f-d8f61181b3bd)

**Comment by EGYT5453** [comment]
hura...
